spring:
  application:
    name: expense_tracker

  r2dbc:
    url: r2dbc:pool:postgresql://localhost:5432/expense_db
    username: shiva
    password: shiva

  devtools:
    restart:
      enabled: true
      poll-interval: 1s
      quiet-period: 400ms

  web:
    cors:
      mappings:
        "/**":
          allowed-origins: "*"
          allowed-methods: GET,POST,PUT,DELETE,OPTIONS
          allowed-headers: "*"
          allow-credentials: false
